export const POPULAR_FONTS = [
    "Inter",
    "Roboto",
    "Open Sans",
    "Lato",
    "Montserrat",
    "Raleway",
    "Poppins",
    "Nunito",
    "Ubuntu",
    "Rubik",
    "Oswald",
    "Merriweather",
    "PT Sans",
    "Noto Sans",
    "Mukta",
    "Lora",
    "Work Sans",
    "Fira Sans",
    "Quicksand",
    "Barlow",
    "Mulish",
    "Titillium Web",
    "Inconsolata",
    "Kanit",
    "Heebo",
    "Oxygen",
    "DM Sans",
    "Bitter",
    "Cabin",
    "Hind",
    "Arvo",
    "Anton",
    "Josefin Sans",
    "Libre Baskerville",
    "Karla",
    "Dosis",
    "Manrope",
    "PT Serif",
    "Nanum Gothic",
    "Cairo",
    "Fjalla One",
    "Exo 2",
    "Dancing Script",
    "Pacifico",
    "Shadows Into Light",
    "Indie Flower",
    "Abril Fatface",
    "Bebas Neue",
    "Lobster",
    "Comfortaa",
    "Righteous",
    "Fredoka One",
    "Permanent Marker",
    "Alfa Slab One",
    "Chakra Petch",
    "Press Start 2P",
    "Audiowide",
    "Creepster",
    "Bangers",
    "Orbitron",
    "Satisfy",
    "Great Vibes",
    "Courgette",
    "Kalam",
    "Kaushan Script",
    "Sacramento",
    "Cookie",
    "Amatic SC",
    "Caveat",
    "Covered By Your Grace",
    "Patrick Hand",
    "Neucha",
    "Gloria Hallelujah",
    "Architects Daughter",
    "Coming Soon",
    "Handlee",
    "Nothing You Could Do",
    "Zeyada",
    "Reenie Beanie",
    "Waiting for the Sunrise",
    "Just Me Again Down Here",
    "Homemade Apple",
    "La Belle Aurore",
    "Cedarville Cursive",
    "Kristi",
    "Mr Dafoe",
    "Mrs Saint Delafield",
    "Pinyon Script",
    "Rouge Script",
    "Aguafina Script",
    "Meddon",
    "Stalemate",
    "Monsieur La Doulaise",
    "Miss Fajardose",
    "Herr Von Muellerhoff",
    "Meie Script",
    "Felipa",
    "Jim Nightshade",
    "UnifrakturMaguntia",
    "UnifrakturCook",
    "Pirata One",
    "Sancreek",
    "Rye",
    "Ewert",
    "Frijole",
    "Creepster",
    "Nosifer",
    "Butcherman",
    "Eater",
    "Fascinate Inline",
    "Faster One",
    "Caesar Dressing",
    "Metal Mania",
    "New Rocker",
    "Trade Winds",
    "Piedra",
    "Kranky"
];
