export interface ThemeDefinition {
    id: string;
    name: string;
    type: "light" | "dark";
    colors: {
        "--color-canvas-default": string;
        "--color-canvas-subtle": string;
        "--color-border-default": string;
        "--color-border-muted": string;
        "--color-fg-default": string;
        "--color-fg-muted": string;
        "--color-accent-fg": string;
        "--color-accent-emphasis": string;
        "--color-success-fg": string;
        "--color-attention-fg": string;
        "--color-danger-emphasis": string;
        "--color-btn-text": string;
        "--color-btn-bg": string;
        "--color-btn-border": string;
        "--color-btn-hover-bg": string;
        "--color-btn-hover-border": string;
        "--color-btn-selected-bg": string;
        "--color-btn-primary-bg": string;
        "--color-btn-primary-border": string;
        "--color-btn-primary-text": string;
        "--color-btn-primary-hover-bg": string;
        "--color-action-list-item-active-bg": string;
    };
}

export const PRESET_THEMES: ThemeDefinition[] = [
    {
        id: "github-dark",
        name: "GitHub Dark",
        type: "dark",
        colors: {
            "--color-canvas-default": "#0d1117",
            "--color-canvas-subtle": "#161b22",
            "--color-border-default": "#30363d",
            "--color-border-muted": "#21262d",
            "--color-fg-default": "#c9d1d9",
            "--color-fg-muted": "#8b949e",
            "--color-accent-fg": "#58a6ff",
            "--color-accent-emphasis": "#1f6feb",
            "--color-success-fg": "#3fb950",
            "--color-attention-fg": "#d29922",
            "--color-danger-emphasis": "#da3633",
            "--color-btn-text": "#c9d1d9",
            "--color-btn-bg": "#21262d",
            "--color-btn-border": "#30363d",
            "--color-btn-hover-bg": "#30363d",
            "--color-btn-hover-border": "#8b949e",
            "--color-btn-selected-bg": "#30363d",
            "--color-btn-primary-bg": "#238636",
            "--color-btn-primary-border": "#2ea043",
            "--color-btn-primary-text": "#ffffff",
            "--color-btn-primary-hover-bg": "#2ea043",
            "--color-action-list-item-active-bg": "#1f6feb26",
        }
    },

    {
        id: "github-dimmed",
        name: "GitHub Dimmed",
        type: "dark",
        colors: {
            "--color-canvas-default": "#22272e",
            "--color-canvas-subtle": "#2d333b",
            "--color-border-default": "#444c56",
            "--color-border-muted": "#373e47",
            "--color-fg-default": "#adbac7",
            "--color-fg-muted": "#768390",
            "--color-accent-fg": "#539bf5",
            "--color-accent-emphasis": "#316dca",
            "--color-success-fg": "#57ab5a",
            "--color-attention-fg": "#c69026",
            "--color-danger-emphasis": "#e5534b",
            "--color-btn-text": "#adbac7",
            "--color-btn-bg": "#373e47",
            "--color-btn-border": "#444c56",
            "--color-btn-hover-bg": "#444c56",
            "--color-btn-hover-border": "#768390",
            "--color-btn-selected-bg": "#444c56",
            "--color-btn-primary-bg": "#347d39",
            "--color-btn-primary-border": "#347d39",
            "--color-btn-primary-text": "#ffffff",
            "--color-btn-primary-hover-bg": "#46954a",
            "--color-action-list-item-active-bg": "#316dca26",
        }
    },
    {
        id: "dracula",
        name: "Dracula",
        type: "dark",
        colors: {
            "--color-canvas-default": "#282a36",
            "--color-canvas-subtle": "#21222c",
            "--color-border-default": "#44475a",
            "--color-border-muted": "#6272a4",
            "--color-fg-default": "#f8f8f2",
            "--color-fg-muted": "#bd93f9",
            "--color-accent-fg": "#ff79c6",
            "--color-accent-emphasis": "#bd93f9",
            "--color-success-fg": "#50fa7b",
            "--color-attention-fg": "#f1fa8c",
            "--color-danger-emphasis": "#ff5555",
            "--color-btn-text": "#f8f8f2",
            "--color-btn-bg": "#44475a",
            "--color-btn-border": "#6272a4",
            "--color-btn-hover-bg": "#6272a4",
            "--color-btn-hover-border": "#bd93f9",
            "--color-btn-selected-bg": "#44475a",
            "--color-btn-primary-bg": "#bd93f9",
            "--color-btn-primary-border": "#bd93f9",
            "--color-btn-primary-text": "#282a36",
            "--color-btn-primary-hover-bg": "#ff79c6",
            "--color-action-list-item-active-bg": "#bd93f926",
        }
    },
    {
        id: "nord",
        name: "Nord",
        type: "dark",
        colors: {
            "--color-canvas-default": "#2e3440",
            "--color-canvas-subtle": "#3b4252",
            "--color-border-default": "#434c5e",
            "--color-border-muted": "#4c566a",
            "--color-fg-default": "#d8dee9",
            "--color-fg-muted": "#a2bf8a",
            "--color-accent-fg": "#88c0d0",
            "--color-accent-emphasis": "#81a1c1",
            "--color-success-fg": "#a3be8c",
            "--color-attention-fg": "#ebcb8b",
            "--color-danger-emphasis": "#bf616a",
            "--color-btn-text": "#d8dee9",
            "--color-btn-bg": "#3b4252",
            "--color-btn-border": "#434c5e",
            "--color-btn-hover-bg": "#434c5e",
            "--color-btn-hover-border": "#81a1c1",
            "--color-btn-selected-bg": "#434c5e",
            "--color-btn-primary-bg": "#88c0d0",
            "--color-btn-primary-border": "#88c0d0",
            "--color-btn-primary-text": "#2e3440",
            "--color-btn-primary-hover-bg": "#81a1c1",
            "--color-action-list-item-active-bg": "#88c0d026",
        }
    },
    {
        id: "monokai",
        name: "Monokai",
        type: "dark",
        colors: {
            "--color-canvas-default": "#272822",
            "--color-canvas-subtle": "#1e1f1c",
            "--color-border-default": "#49483e",
            "--color-border-muted": "#75715e",
            "--color-fg-default": "#f8f8f2",
            "--color-fg-muted": "#75715e",
            "--color-accent-fg": "#66d9ef",
            "--color-accent-emphasis": "#fd971f",
            "--color-success-fg": "#a6e22e",
            "--color-attention-fg": "#e6db74",
            "--color-danger-emphasis": "#f92672",
            "--color-btn-text": "#f8f8f2",
            "--color-btn-bg": "#3e3d32",
            "--color-btn-border": "#49483e",
            "--color-btn-hover-bg": "#49483e",
            "--color-btn-hover-border": "#66d9ef",
            "--color-btn-selected-bg": "#3e3d32",
            "--color-btn-primary-bg": "#f92672",
            "--color-btn-primary-border": "#f92672",
            "--color-btn-primary-text": "#f8f8f2",
            "--color-btn-primary-hover-bg": "#ff4081",
            "--color-action-list-item-active-bg": "#f9267226",
        }
    },

    {
        id: "solarized-dark",
        name: "Solarized Dark",
        type: "dark",
        colors: {
            "--color-canvas-default": "#002b36",
            "--color-canvas-subtle": "#073642",
            "--color-border-default": "#586e75",
            "--color-border-muted": "#657b83",
            "--color-fg-default": "#839496",
            "--color-fg-muted": "#586e75",
            "--color-accent-fg": "#268bd2",
            "--color-accent-emphasis": "#2aa198",
            "--color-success-fg": "#859900",
            "--color-attention-fg": "#b58900",
            "--color-danger-emphasis": "#dc322f",
            "--color-btn-text": "#839496",
            "--color-btn-bg": "#073642",
            "--color-btn-border": "#586e75",
            "--color-btn-hover-bg": "#586e75",
            "--color-btn-hover-border": "#93a1a1",
            "--color-btn-selected-bg": "#073642",
            "--color-btn-primary-bg": "#2aa198",
            "--color-btn-primary-border": "#2aa198",
            "--color-btn-primary-text": "#002b36",
            "--color-btn-primary-hover-bg": "#268bd2",
            "--color-action-list-item-active-bg": "#2aa19826",
        }
    },
    {
        id: "ayu-dark",
        name: "Ayu Dark",
        type: "dark",
        colors: {
            "--color-canvas-default": "#0b0e14",
            "--color-canvas-subtle": "#131721",
            "--color-border-default": "#253340",
            "--color-border-muted": "#141925",
            "--color-fg-default": "#bfbdb6",
            "--color-fg-muted": "#6c7380",
            "--color-accent-fg": "#39bae6",
            "--color-accent-emphasis": "#59c2ff",
            "--color-success-fg": "#7fd962",
            "--color-attention-fg": "#e6b450",
            "--color-danger-emphasis": "#d95757",
            "--color-btn-text": "#bfbdb6",
            "--color-btn-bg": "#131721",
            "--color-btn-border": "#253340",
            "--color-btn-hover-bg": "#19202f",
            "--color-btn-hover-border": "#3e4b59",
            "--color-btn-selected-bg": "#1d2433",
            "--color-btn-primary-bg": "#39bae6",
            "--color-btn-primary-border": "#39bae6",
            "--color-btn-primary-text": "#0b0e14",
            "--color-btn-primary-hover-bg": "#59c2ff",
            "--color-action-list-item-active-bg": "#39bae620"
        }
    },
    {
        id: "ayu-mirage",
        name: "Ayu Mirage",
        type: "dark",
        colors: {
            "--color-canvas-default": "#1f2430",
            "--color-canvas-subtle": "#232834",
            "--color-border-default": "#191e2a",
            "--color-border-muted": "#171b26",
            "--color-fg-default": "#cbccc6",
            "--color-fg-muted": "#707a8c",
            "--color-accent-fg": "#5ccfe6",
            "--color-accent-emphasis": "#73d0ff",
            "--color-success-fg": "#bae67e",
            "--color-attention-fg": "#ffd580",
            "--color-danger-emphasis": "#ff3333",
            "--color-btn-text": "#cbccc6",
            "--color-btn-bg": "#232834",
            "--color-btn-border": "#191e2a",
            "--color-btn-hover-bg": "#2a303e",
            "--color-btn-hover-border": "#343d4f",
            "--color-btn-selected-bg": "#2d3445",
            "--color-btn-primary-bg": "#5ccfe6",
            "--color-btn-primary-border": "#5ccfe6",
            "--color-btn-primary-text": "#1f2430",
            "--color-btn-primary-hover-bg": "#73d0ff",
            "--color-action-list-item-active-bg": "#5ccfe620"
        }
    },

    {
        id: "catppuccin-frappe",
        name: "Catppuccin Frappe",
        type: "dark",
        colors: {
            "--color-canvas-default": "#303446",
            "--color-canvas-subtle": "#292c3c",
            "--color-border-default": "#414559",
            "--color-border-muted": "#51576d",
            "--color-fg-default": "#c6d0f5",
            "--color-fg-muted": "#a5adce",
            "--color-accent-fg": "#8caaee",
            "--color-accent-emphasis": "#babbf1",
            "--color-success-fg": "#a6d189",
            "--color-attention-fg": "#e5c890",
            "--color-danger-emphasis": "#e78284",
            "--color-btn-text": "#c6d0f5",
            "--color-btn-bg": "#292c3c",
            "--color-btn-border": "#414559",
            "--color-btn-hover-bg": "#414559",
            "--color-btn-hover-border": "#626880",
            "--color-btn-selected-bg": "#414559",
            "--color-btn-primary-bg": "#8caaee",
            "--color-btn-primary-border": "#8caaee",
            "--color-btn-primary-text": "#303446",
            "--color-btn-primary-hover-bg": "#babbf1",
            "--color-action-list-item-active-bg": "#8caaee20"
        }
    },
    {
        id: "catppuccin-macchiato",
        name: "Catppuccin Macchiato",
        type: "dark",
        colors: {
            "--color-canvas-default": "#24273a",
            "--color-canvas-subtle": "#1e2030",
            "--color-border-default": "#363a4f",
            "--color-border-muted": "#494d64",
            "--color-fg-default": "#cad3f5",
            "--color-fg-muted": "#a5adcb",
            "--color-accent-fg": "#8aadf4",
            "--color-accent-emphasis": "#b7bdf8",
            "--color-success-fg": "#a6da95",
            "--color-attention-fg": "#eed49f",
            "--color-danger-emphasis": "#ed8796",
            "--color-btn-text": "#cad3f5",
            "--color-btn-bg": "#1e2030",
            "--color-btn-border": "#363a4f",
            "--color-btn-hover-bg": "#363a4f",
            "--color-btn-hover-border": "#5b6078",
            "--color-btn-selected-bg": "#363a4f",
            "--color-btn-primary-bg": "#8aadf4",
            "--color-btn-primary-border": "#8aadf4",
            "--color-btn-primary-text": "#24273a",
            "--color-btn-primary-hover-bg": "#b7bdf8",
            "--color-action-list-item-active-bg": "#8aadf420"
        }
    },
    {
        id: "catppuccin-mocha",
        name: "Catppuccin Mocha",
        type: "dark",
        colors: {
            "--color-canvas-default": "#1e1e2e",
            "--color-canvas-subtle": "#181825",
            "--color-border-default": "#313244",
            "--color-border-muted": "#45475a",
            "--color-fg-default": "#cdd6f4",
            "--color-fg-muted": "#a6adc8",
            "--color-accent-fg": "#89b4fa",
            "--color-accent-emphasis": "#b4befe",
            "--color-success-fg": "#a6e3a1",
            "--color-attention-fg": "#f9e2af",
            "--color-danger-emphasis": "#f38ba8",
            "--color-btn-text": "#cdd6f4",
            "--color-btn-bg": "#181825",
            "--color-btn-border": "#313244",
            "--color-btn-hover-bg": "#313244",
            "--color-btn-hover-border": "#585b70",
            "--color-btn-selected-bg": "#313244",
            "--color-btn-primary-bg": "#89b4fa",
            "--color-btn-primary-border": "#89b4fa",
            "--color-btn-primary-text": "#1e1e2e",
            "--color-btn-primary-hover-bg": "#b4befe",
            "--color-action-list-item-active-bg": "#89b4fa20"
        }
    },
    {
        id: "tokyo-night",
        name: "Tokyo Night",
        type: "dark",
        colors: {
            "--color-canvas-default": "#1a1b26",
            "--color-canvas-subtle": "#16161e",
            "--color-border-default": "#24283b",
            "--color-border-muted": "#414868",
            "--color-fg-default": "#c0caf5",
            "--color-fg-muted": "#a9b1d6",
            "--color-accent-fg": "#7aa2f7",
            "--color-accent-emphasis": "#bb9af7",
            "--color-success-fg": "#9ece6a",
            "--color-attention-fg": "#e0af68",
            "--color-danger-emphasis": "#f7768e",
            "--color-btn-text": "#c0caf5",
            "--color-btn-bg": "#16161e",
            "--color-btn-border": "#24283b",
            "--color-btn-hover-bg": "#292e42",
            "--color-btn-hover-border": "#565f89",
            "--color-btn-selected-bg": "#292e42",
            "--color-btn-primary-bg": "#7aa2f7",
            "--color-btn-primary-border": "#7aa2f7",
            "--color-btn-primary-text": "#1a1b26",
            "--color-btn-primary-hover-bg": "#bb9af7",
            "--color-action-list-item-active-bg": "#7aa2f720"
        }
    },
    {
        id: "cobalt2",
        name: "Cobalt2",
        type: "dark",
        colors: {
            "--color-canvas-default": "#193549",
            "--color-canvas-subtle": "#15232d",
            "--color-border-default": "#0d3a58",
            "--color-border-muted": "#35434d",
            "--color-fg-default": "#ffffff",
            "--color-fg-muted": "#859dc3",
            "--color-accent-fg": "#0088ff",
            "--color-accent-emphasis": "#ffc600",
            "--color-success-fg": "#3ad900",
            "--color-attention-fg": "#ffeb3b",
            "--color-danger-emphasis": "#ff0000",
            "--color-btn-text": "#ffffff",
            "--color-btn-bg": "#15232d",
            "--color-btn-border": "#0d3a58",
            "--color-btn-hover-bg": "#1f4662",
            "--color-btn-hover-border": "#0088ff",
            "--color-btn-selected-bg": "#1f4662",
            "--color-btn-primary-bg": "#0088ff",
            "--color-btn-primary-border": "#0088ff",
            "--color-btn-primary-text": "#ffffff",
            "--color-btn-primary-hover-bg": "#ffc600",
            "--color-action-list-item-active-bg": "#0088ff20"
        }
    },
    {
        id: "shades-of-purple",
        name: "Shades of Purple",
        type: "dark",
        colors: {
            "--color-canvas-default": "#2d2b55",
            "--color-canvas-subtle": "#1e1e3f",
            "--color-border-default": "#494588",
            "--color-border-muted": "#58529e",
            "--color-fg-default": "#ffffff",
            "--color-fg-muted": "#a599e9",
            "--color-accent-fg": "#b362ff",
            "--color-accent-emphasis": "#fad000",
            "--color-success-fg": "#3ad900",
            "--color-attention-fg": "#ff9d00",
            "--color-danger-emphasis": "#ec5f67",
            "--color-btn-text": "#ffffff",
            "--color-btn-bg": "#1e1e3f",
            "--color-btn-border": "#494588",
            "--color-btn-hover-bg": "#2d2b55",
            "--color-btn-hover-border": "#fad000",
            "--color-btn-selected-bg": "#2d2b55",
            "--color-btn-primary-bg": "#fad000",
            "--color-btn-primary-border": "#fad000",
            "--color-btn-primary-text": "#2d2b55",
            "--color-btn-primary-hover-bg": "#b362ff",
            "--color-action-list-item-active-bg": "#b362ff20"
        }
    },
    {
        id: "synthwave-84",
        name: "Synthwave '84",
        type: "dark",
        colors: {
            "--color-canvas-default": "#2b213a",
            "--color-canvas-subtle": "#261b2e",
            "--color-border-default": "#493b5a",
            "--color-border-muted": "#614d7a",
            "--color-fg-default": "#f92aad",
            "--color-fg-muted": "#756a84",
            "--color-accent-fg": "#f92aad",
            "--color-accent-emphasis": "#72f1b8",
            "--color-success-fg": "#06d6a0",
            "--color-attention-fg": "#ffd166",
            "--color-danger-emphasis": "#fe4a49",
            "--color-btn-text": "#f92aad",
            "--color-btn-bg": "#261b2e",
            "--color-btn-border": "#493b5a",
            "--color-btn-hover-bg": "#241b2f", 
            "--color-btn-hover-border": "#f92aad",
            "--color-btn-selected-bg": "#241b2f",
            "--color-btn-primary-bg": "#f92aad",
            "--color-btn-primary-border": "#f92aad",
            "--color-btn-primary-text": "#2b213a",
            "--color-btn-primary-hover-bg": "#ff7edb",
            "--color-action-list-item-active-bg": "#f92aad20"
        }
    },
    {
        id: "rose-pine",
        name: "Rosé Pine",
        type: "dark",
        colors: {
            "--color-canvas-default": "#191724",
            "--color-canvas-subtle": "#1f1d2e",
            "--color-border-default": "#26233a",
            "--color-border-muted": "#403d52",
            "--color-fg-default": "#e0def4",
            "--color-fg-muted": "#908caa",
            "--color-accent-fg": "#c4a7e7",
            "--color-accent-emphasis": "#ebbcba",
            "--color-success-fg": "#9ccfd8",
            "--color-attention-fg": "#f6c177",
            "--color-danger-emphasis": "#eb6f92",
            "--color-btn-text": "#e0def4",
            "--color-btn-bg": "#1f1d2e",
            "--color-btn-border": "#26233a",
            "--color-btn-hover-bg": "#26233a",
            "--color-btn-hover-border": "#524f67",
            "--color-btn-selected-bg": "#26233a",
            "--color-btn-primary-bg": "#c4a7e7",
            "--color-btn-primary-border": "#c4a7e7",
            "--color-btn-primary-text": "#191724",
            "--color-btn-primary-hover-bg": "#ebbcba",
            "--color-action-list-item-active-bg": "#c4a7e720"
        }
    },
    {
        id: "rose-pine-moon",
        name: "Rosé Pine Moon",
        type: "dark",
        colors: {
            "--color-canvas-default": "#232136",
            "--color-canvas-subtle": "#2a273f",
            "--color-border-default": "#393552",
            "--color-border-muted": "#44415a",
            "--color-fg-default": "#e0def4",
            "--color-fg-muted": "#908caa",
            "--color-accent-fg": "#c4a7e7",
            "--color-accent-emphasis": "#ea9a97",
            "--color-success-fg": "#9ccfd8",
            "--color-attention-fg": "#f6c177",
            "--color-danger-emphasis": "#eb6f92",
            "--color-btn-text": "#e0def4",
            "--color-btn-bg": "#2a273f",
            "--color-btn-border": "#393552",
            "--color-btn-hover-bg": "#393552",
            "--color-btn-hover-border": "#56526e",
            "--color-btn-selected-bg": "#393552",
            "--color-btn-primary-bg": "#c4a7e7",
            "--color-btn-primary-border": "#c4a7e7",
            "--color-btn-primary-text": "#232136",
            "--color-btn-primary-hover-bg": "#ea9a97",
            "--color-action-list-item-active-bg": "#c4a7e720"
        }
    },

];

export const getThemeById = (id: string): ThemeDefinition => {
    return PRESET_THEMES.find(t => t.id === id) || PRESET_THEMES[0];
};
